/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package pkg;

public interface MyNewGrammarTreeConstants
{
  public int JJTONE_LINE = 0;
  public int JJTXPRO = 1;
  public int JJTBLOCKS = 2;
  public int JJTDECLARATIONS = 3;
  public int JJTSTATEMENTS = 4;
  public int JJTIFSTATEMENT = 5;
  public int JJTLOOPSTATEMENT = 6;
  public int JJTINTEGRAL = 7;
  public int JJTLHS = 8;
  public int JJTRHS = 9;
  public int JJTOUTPUTSTATEMENT = 10;
  public int JJTEXPRESSION = 11;
  public int JJTCOMPARISON = 12;
  public int JJTVARIABLE = 13;


  public String[] jjtNodeName = {
    "one_line",
    "xpro",
    "blocks",
    "declarations",
    "statements",
    "ifstatement",
    "loopstatement",
    "Integral",
    "LHS",
    "RHS",
    "outputstatement",
    "expression",
    "comparison",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=d26e0bc5a6b49938b8929e30fd067100 (do not edit this line) */
